kind: Service
apiVersion: v1
metadata:
  name: "rabbitmq"
  annotations:
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: "rabbitmq"
  ports:
    - protocol: "TCP"
      port: 5672
      targetPort: 5672