---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-prom-rule
  namespace: default
  labels:
    prometheus: prometheus # This label is configured as part of the installation of the prometheus operator
spec: 
  groups:
  - name: rabbitmq # Define the name of your rule
    rules:
    - record: rabbitmq_queue_messages # The name of the metrics you want
      expr: rabbitmq_queue_messages{queue="toWorker"} # Query to make to prometheus
      labels:
        namespace: default
        service: rabbitmq-exporter # Name of the service you are going to configure your HPA with