##
## You provide this
##

FROM python:3.7

CMD mkdir /moviecolor
WORKDIR /moviecolor

RUN pip3 install --upgrade pika redis jsonpickle requests flask pillow

COPY . /moviecolor

CMD cd /moviecolor && \
    python3 worker-server.py