##
## You provide this
##

FROM python:3.7

CMD mkdir /app
WORKDIR /app

RUN pip3 install --upgrade requests numpy scikit-learn pillow opencv-python matplotlib gcloud google-api-python-client flask jsonpickle pika redis colormath

COPY . /app

EXPOSE 5000
CMD cd /app && \
    python3 rest-server.py