##
## You provide this
##

FROM python:3.7

ADD logs.py /

RUN pip3 install --upgrade pika redis jsonpickle requests flask

CMD mkdir /app
WORKDIR /app

COPY . /app

CMD cd /app && \
    python3 logs.py